X-RapidAPI-Key:
scheduler:
  interval-in-crone: '* * * * * ?'
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/weather_analyzer
    username: root
  jpa:
    show-sql: true
server:
  port: 9080
